<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ABotDirectTest</RootNamespace>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DisableImplicitFrameworkReferences>false</DisableImplicitFrameworkReferences>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ABot">
      <HintPath>Mods\ABot\bin\Debug\net10.0-windows\ABot.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
