param(
    [Parameter(Mandatory = $true)]
    [string]$VersionFile,

    [Parameter(Mandatory = $true)]
    [string]$ManifestFile,

    [Parameter(Mandatory = $true)]
    [string]$GeneratedCodeFile,

    [switch]$Increment
)

$ErrorActionPreference = 'Stop'

$current = ([System.IO.File]::ReadAllText($VersionFile)).Trim()
$match = [System.Text.RegularExpressions.Regex]::Match($current, '^(\d+)\.(\d+)\.(\d+)$')
if (-not $match.Success) {
    throw "Invalid portable Mod version '$current'. Expected MAJOR.MINOR.PATCH."
}

$major = [int]$match.Groups[1].Value
$minor = [int]$match.Groups[2].Value
$patch = [int]$match.Groups[3].Value
if ($Increment) {
    if ($patch -eq [int]::MaxValue) {
        throw 'Patch version reached Int32.MaxValue.'
    }
    $patch++
}
$version = "$major.$minor.$patch"

if ($Increment) {
    [System.IO.File]::WriteAllText($VersionFile, $version + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

$manifestJsonText = [System.IO.File]::ReadAllText($ManifestFile, [System.Text.Encoding]::UTF8)
$manifest = $manifestJsonText | ConvertFrom-Json
$manifest.version = $version
$manifestJson = $manifest | ConvertTo-Json -Depth 20
[System.IO.File]::WriteAllText($ManifestFile, $manifestJson + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))

$generatedDirectory = [System.IO.Path]::GetDirectoryName($GeneratedCodeFile)
[System.IO.Directory]::CreateDirectory($generatedDirectory) | Out-Null
$escapedVersion = $version.Replace('"', '\"')
$source = @"
// <auto-generated />
namespace MeguminDuel;

internal static class PortableBuildInfo
{
    internal const string Version = "$escapedVersion";
}
"@
[System.IO.File]::WriteAllText($GeneratedCodeFile, $source, [System.Text.UTF8Encoding]::new($false))

Write-Output $version
